name: built_highcharts
description: An absolute bare-bones web app.
version: 0.0.1
#homepage: https://www.example.com
#author: Tsushko <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  path: ^1.4.1
  built_value: any
  build_runner: any
  source_gen: any
  built_value_generator: any
