name: built_highcharts
description: An absolute bare-bones web app.
version: 0.1.2
homepage: https://github.com/vadimtsushko/built_highcharts
author: Vadim Tsushko vadimtsushko@gmail.com

environment:
  sdk:  '>=1.24.3 <2.0.0'
dependencies:
  path: any
  built_value: "4.6.1"
  js: any
dev_dependencies:
  test: any
  build_runner: ^0.6.0
  built_value_generator: "4.6.1"
