description: "An absolute bare-bones web app."
name: "built_highcharts"
version: "0.0.1"
dependencies: 
  build_runner: "any"
  built_value: "any"
  built_value_generator: "any"
  js: "any"
  path: "^1.4.1"
  source_gen: "any"
dev_dependencies: 
  test: ">=0.12.0"
environment: 
  sdk: ">=1.20.1 <2.0.0"
