name: 'built_highchart_demo'
version: 0.0.1
description: An absolute bare-bones web app.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  yaml: any
  built_highcharts:
    path: ../
web:
  compiler:
    debug: dartdevc
dev_dependencies:
  build_runner: ^0.7.0
  build_web_compilers: ^0.2.0